#!/usr/bin/env perl
use strict;
use warnings;
use utf8::all;
use Encode 'decode_utf8';
use File::Slurp 'slurp';
use autodie;

my $file = shift;

my $msg = decode_utf8 slurp($file);
exit 0 unless $msg =~ /^#\s*modified:\s*japanese.pl$/m && $msg =~ /^#\s*modified:/mg == 1;
my $new_words = join '、', $msg =~ /^\+\s*word\s*=>\s*['"](.+)['"],\s*$/gm;
exit 0 unless $new_words;
$msg =~ s/^/$new_words/;
open my $fh, '>', $file;
print $fh $msg;
close $fh;

